### PR TITLE
Fix for Salmon 0.14 num_targets -> num_valid_targets issue.

### LINKED ISSUE #29: Importing transcript abundance datasets generated with Salmon 0.14.0
Hi!
I have recently updated Salmon to the latest version (0.14.0) and I'm not anymore able to import Salmon outputs into R using the code
tximport(file, type = "salmon", txOut = TRUE, countsFromAbundance = "no")

This is the error that I get when I run the code above:

txi <- tximport(file, type = "salmon", txOut = TRUE, countsFromAbundance = "no")
reading in files with read_tsv
Error in readBin(bootCon, "integer", n = expected.n) :
  invalid 'n' argument

Any suggestion?
Thanks

Edo

### PR DESCRIPTION
**Pull request by roryk**
This is the same gotcha as in bcbio/bcbio-nextgen#2843.

Fixes #29.

Test data to show this fixes the issue can be grabbed here: https://www.dropbox.com/s/d5325xe3weo8io2/tximport-example.tar.gz?dl=1

### CODE REVIEW

**Comment by mikelove** [comment]
Thanks Rory, I’ll pull this ASAP

**Comment by roryk** [comment]
Thanks Mike!

**Comment by rob-p** [comment]
Hi guys (@roryk  & @mikelove), sorry for the unintended consequences of that naming change!

**Comment by roryk** [comment]
@rob-p No worries!

**Comment by mikelove** [comment]
I just bumped the version number so this is v1.13.3 in the devel branch.

**Comment by roryk** [comment]
Thanks, does this get updated on bioconductor, or does that only happen when there is a new official bioconductor release? I'm wondering how to update the bioconductor-tximport bioconda recipe so this fix gets pulled in.

**Comment by mikelove** [comment]
I'll push to release as well, and it should propagate in 1-2 days.

**Comment by roryk** [comment]
Great, thanks for the quick merge and fix Mike!

**Comment by mikelove** [comment]
Just pushed 1.12.1 which usually is available by ~1pm US East tomorrow.

**Comment by roryk** [comment]
Awesome 1.12.1 showed up on bioconductor today-- I updated the bioconda package so we should be good to go now. Thanks a bunch Mike!

**Pull request merged**
